##
# Vips is generally the best image compression library,
# this works well on  and infratructure.d
#
# For Beach override, see also
# Configuration/Production/Beach/Instance/Settings.yaml
##
Neos:
  Imagine:
    driver: 'Vips'
    enabledDrivers:
      Vips: true
      Gd: true
      Imagick: true
  Media:
    image:
      defaultOptions:
        # The Vips driver does not support interlace
        interlace: ~

Sitegeist:
  Kaleidoscope:
    dummyImage:
      overrideImagineDriver: 'Imagick'
