builder:
  steps:
    build-assets:
      executor: docker
      image: 'node:14-buster'
      script:
        - apt-get update
        - apt-get install -y --no-install-recommends --no-install-suggests build-essential git libjpeg-dev libpng-dev
        - cd ${BEACH_BUILD_WORKSPACE_PATH}/DistributionPackages/CodeQ.Site/Resources/Private/Fusion
        - npx tailwindcss -i ./index.css -o ../../Public/index.css
