Neos:
  Seo:
    socialProfile:
      # type: 'Organization'
      # logo: 'resource://CodeQ.Site/Public/Frontend/XXX.png'
      # profiles:
      #   facebook: ''
      #   linkedIn: ''
      #   instagram: ''
      #   twitter: ''
      #   youTube: ''
