Neos:
  Neos:
    userInterface:
      editPreviewModes:
        # based on most used device 2020
        # https://gs.statcounter.com/screen-resolution-stats/all/europe
        tablet:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Tablet'
          width: 768px
          height: 1024px
        mobile:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: ''
          title: 'Mobile'
          width: 360px
          height: 640px
